use_frameworks!

platform :ios, '9.0'

target 'SKImageExtensionZuoYu_Example' do
  pod 'SKImageExtensionZuoYu', :path => '../'

  target 'SKImageExtensionZuoYu_Tests' do
    inherit! :search_paths

    
  end
end
